[package]
name = "chattium-oxide-server"
version = "0.1.0"
authors = ["nabijaczleweli <nabijaczleweli@gmail.com>"]


[dependencies]
chattium-oxide-lib = { git = "https://github.com/nabijaczleweli/chattium-oxide-lib.git" }
hyper = "0.7"
